name: Basic Checks Workflow

on:
  workflow_call:
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache temp files
        uses: actions/cache@v3
        with:
          path: tmp-cache
          key: ${{ runner.os }}-basic-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-basic-cache-

      - name: Verify secret
        run: |
          if [ -z "${{ secrets.ACCESS_TOKEN }}" ]; then
            echo "❌ Secret is missing!"
            exit 1
          else
            echo "✅ Secret received successfully!"
          fi

      - name: Run setup check
        run: echo "✅ Repository checked out successfully!"

      - name: Run sample validation
        run: echo "🚀 Basic reusable workflow is running with caching enabled."
